from ..typing import YT_COMMENT_MODERATION


BASIC: YT_COMMENT_MODERATION = "Basic"
STRICT: YT_COMMENT_MODERATION = "Strict"
HOLD_ALL: YT_COMMENT_MODERATION = "Hold all"

YT_COMMENT_MODERATIONS = [BASIC, STRICT, HOLD_ALL]
