from .indexes import YT_EDUCATION_TYPES_TO_INDEX
from ..typing import YT_EDUCATION_TYPE


ACTIVITY: YT_EDUCATION_TYPE = "Activity"
CONCEPT_OVERVIEW: YT_EDUCATION_TYPE = "Concept overview"
HOW_TO: YT_EDUCATION_TYPE = "How-to"
LECTURE: YT_EDUCATION_TYPE = "Lecture"
PROBLEM_WALKTHROUGH: YT_EDUCATION_TYPE = "Problem walkthrough"
REAL_LIFE_APPLICATION: YT_EDUCATION_TYPE = "Real life application"
SCIENCE_EXPERIMENT: YT_EDUCATION_TYPE = "Science Experiment"
TIPS: YT_EDUCATION_TYPE = "Tips"

YT_EDUCATION_TYPES = list(YT_EDUCATION_TYPES_TO_INDEX.keys())
