class YTError(Exception): ...
class YTPageLoadingError(YTError): ...
class YTVideoError(YTError): ...
class YTVideoFormatError(YTError): ...
class YTVUserDataDirError(YTError): ...
class YTStateGroupError(YTError): ...

class YTWarning(Warning): ...
